config/routes.rb
Rails.application.routes.draw do

	root to: "users#home"

  resources :portfolios
	get '/stack', to: 'users#stack'
  resources :users
  resources :groups
  post "/groups/:id/participation", to: "groups#join"

  resources :stocks, controller: 'base_stocks'
  resources :owned_stocks

# User session routes
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	# needed to use number_to_currency
	include ActionView::Helpers::NumberHelper
	belongs_to :group
	belongs_to :user
	has_many :owned_stocks

	validates :group_id, :user_id, :cash, presence: true
	validates :cash, numericality: {greater_than: 0}


	def name
		self.group.name
	end

	def calculate_equity
		equity = 0
		self.owned_stocks.each do |stock|
      equity += stock.total_value
    end
    equity
	end

	def calculate_value
		if self.owned_stocks.present?
			self.current_value = self.stocks_value + self.cash
			self.save
		else
			self.current_value = self.cash
			self.save
		end
	end

	def stocks_value
		total_value = 0
		self.owned_stocks.each do |stock|
			total_value += stock.quantity * stock.current_market_price
		end
		total_value
	end

	def buy_display
		display_cash = number_to_currency(cash)
		"#{name} | Cash Remaining #{display_cash}"
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
before_action :find_portfolio, only:[:show, :edit, :update, :destroy]

  def index
    @portfolios = Portfolio.all
  end

  def show
    @portfolio.calculate_value
    @owned_stocks = @portfolio.owned_stocks.all
    @equity = @portfolio.calculate_equity || 0
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
  end

  def edit
  end

  def update
    if params[:stock_id] && params[:stock_quantity]
      @owned_stock = @portfolio.owned_stocks.find(params[:stock_id])
      cash = @owned_stock.sell_stock(params[:stock_quantity].to_i)
      current_user.logs.create({
        action: "sell",
        return_amount: cash,
        base_stock_id: @owned_stock.base_stock.id,
        group_id: @portfolio.group.id})
      @portfolio.cash += cash
      @portfolio.save
    end
  end

  def destroy
  end

  private
  def find_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:current_value, :cash)
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_owned_stock.html.erb
<td class="stock-ticker">
	<%= owned_stock.ticker %>
	<img class="stock-chart" src="http://chart.finance.yahoo.com/z?s=<%= owned_stock.ticker %>&t=1d&q=l&l=on&z=s">
</td>
<td class="stock-name"><%= link_to owned_stock.name, stock_url(owned_stock.base_stock_id) %></td>
<td class="stock-quantity"><%= owned_stock.quantity%></td>
<td class="stock-buy-price"><%= number_to_currency(owned_stock.buy_price) %></td>
<td class="stock-current-price"><%= number_to_currency(owned_stock.current_market_price) %></td>
<td class="stock-buy-price per-change"><%= owned_stock.change %> (<%= (owned_stock.percent_change*100).round(2) %>%)</td>
<td class="stock-total-value"><%= number_to_currency(owned_stock.total_value) %></td>

<% if owned_stock.portfolio.user == current_user %>
	<%= render partial: "portfolios/sell_button", object: owned_stock, as: 'stock' %>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="portfolio-info">
	<%= portfolio.user.username %>
	<%= portfolio.group.name %>
	<%= portfolio.owned_stocks.first if portfolio.owned_stocks %>
</div>

app/views/portfolios/_sell_button.html.erb
<td><%= form_tag portfolio_path(@portfolio), method: :patch, remote: true, class: 'form-inline' do %>
  <div class="form-group">
    <%= hidden_field_tag :stock_id, stock.id %>
    <%= number_field_tag :stock_quantity, nil, max: stock.quantity, class: "form-control" %>
    <%= submit_tag "Sell", class: "btn btn-default" %>
  </div>
<% end %></td>

app/views/portfolios/index.html.erb
<div id="portfolio-list">
<%= render @portfolios %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
	<h1>	<%= @portfolio.user.username%>'s Portfolio in: <%= @portfolio.group.name%> </h1>
	<div class="table-responsive">
		<table class="table">
			<thead>
        <tr>
          <th>Ticker</th>
          <th>Company Name</th>
          <th>Quantity Owned</th>
          <th>Purchased Price</th>
					<th>Current Market Price</th>
					<th>Change</th>
					<th>Current Value</th>
          <th>Sell Stock</th>
        </tr>
    </thead>
      <tbody id="stocks-table">
        <% @owned_stocks.each do |stock| %>
          <tr id=<%= stock.id %> class="stock-row">
            <%= render partial: "portfolios/owned_stock", object: stock %>
          </tr>
        <% end %>
       </tbody>
		</table>
	</div>
	<div class="row">
		<div class="col-sm-6">
			<h5>Total Equity</h5>
		</div>
		<div class="col-sm-6" id="portfolio-equity">
			<h5><%= number_to_currency(@equity) %></h5>
		</div>
	</div>
	<hr class="portfolio-hr">
	<div class="row">
		<div class="col-sm-6">
			<h5>Cash Holdings</h5>
		</div>
		<div class="col-sm-6" id="portfolio-cash">
			<h5><%=number_to_currency(@portfolio.cash)%></h5>
		</div>
	</div>
	<hr class="portfolio-hr">
	<div class="row">
		<div class="col-sm-6">
			<h5>Total</h5>
		</div>
		<div class="col-sm-6" id="portfolio-total">
			<h5><%= number_to_currency(@portfolio.current_value)%></h5>
		</div>
	</div>
</div>

app/views/portfolios/update.js.erb
if (<%= @owned_stock.quantity %> > 0){
	$('.stock-row#<%= @owned_stock.id %>').html('<%= j(render partial: "portfolios/owned_stock", object: @owned_stock) %>');
} else {
	$('.stock-row#<%= @owned_stock.id %>').remove();
}

$('#portfolio-cash').html('<%= number_to_currency(@portfolio.cash) %>');
$('#portfolio-equity').html('<%= number_to_currency(@portfolio.calculate_equity) %>');
$('#portfolio-total').html('<%= number_to_currency(@portfolio.current_value) %>');