config/routes.rb
Rails.application.routes.draw do

	root to: "users#home"

  resources :portfolios
	get '/stack', to: 'users#stack'
  resources :users
  resources :groups
  post "/groups/:id/participation", to: "groups#join"

  resources :stocks, controller: 'base_stocks'
  resources :owned_stocks

# User session routes
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :participations
	has_many :users, through: :participations
	has_many :portfolios
	has_many :logs

	validates :name, :end_date, :starting_total, :max_size, presence: true
	validates :starting_total, :max_size, numericality: {greater_than: 0}
	validates_datetime :end_date, after: :start_date

	before_validation :set_start_date, on: [:create]

	def set_start_date
		self.start_date = Time.now
	end

	def is_full?
		self.users.size >= self.max_size
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:show, :edit, :update, :destroy, :join]

  def index
    if params[:name]
      @groups = Group.where("LOWER(name) LIKE LOWER(?)", "%#{params[:name]}%").paginate(:page => params[:page])
    else
      @groups = Group.paginate(:page => params[:page])
    end
  end

  def show
    @logs = @group.logs.reverse
    @group.portfolios.each do |portfolio|
      portfolio.calculate_value
    end
  end

  def new
    @group = Group.new
  end

  def create
    @participation = current_user.participations.new
    @group = Group.new(group_params)
    @group.participations << @participation
    @participation.save

    if @group.save
      flash[:notice] = "Your group has been created"
      redirect_to group_path(@group)
    else
      flash[:warning] = "Could not create group"
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def join
    @user = current_user

    unless @group.is_full?
      @user.groups << @group
      redirect_to group_url(@group)
    else
      flash[:warning] = "Sorry, group has a maximum of #{@group.max_size} users."
      redirect_to :back
    end
  end

  private
  def find_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :start_date, :end_date, :starting_total, :max_size)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being made:<h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :starting_total %>
      <%= f.number_field :starting_total, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :max_size %>
      <%= f.number_field :max_size, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :end_date %>
      <%= f.datetime_select :end_date, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
<% end %>

app/views/groups/_group.html.erb
<% @groups.each do |group| %>
  <%= link_to group.name, group_path(group), class: "list-group-item" %>
<% end %>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <div class="search col-sm-8">
      <%= form_tag groups_path, method: :get, remote: true, class: "form-inline" do %>
        <div class="form-group">
          <%= label_tag :name, "Group Search:" %>
          <%= text_field_tag :name, params[:name], class: "form-control" %>
          <%= submit_tag 'Submit', class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
    <div class="new-group col-sm-4">
      <%= link_to "Create a New Group", new_group_url, class: 'btn btn-default', id: "create-group-btn" %>
    </div>
  </div>

  <div id="list-group" class="group-list row">
    <%= render 'group' %>
  </div>
</div>

app/views/groups/index.js.erb
$('#list-group').html("<%= j(render 'group') %>");

app/views/groups/new.html.erb
<div class="container">
  <h1>Create a Group</h1>
  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<div class="jumbotron">
	<div class="container">
		<h1><%= @group.name %></h1>
		<p>Starting Amount: <%= number_to_currency(@group.starting_total) %></p>
		<p>End Date: <%= @group.end_date.localtime.strftime("%A %B %e, %Y at %H:%M") %></p>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<!-- if current user == group creator delete group button -->
			<% if !@group.users.include?(current_user) %>
				<!-- Add button to join group -->

			<%= link_to "Join This Group", "/groups/#{@group.id}/participation", method: :post,  class: "btn btn-default" %>
			<% end %>
			<div class="list-group">
				<h2>Players:</h2>
				<% @group.users.each do |user| %>
					<%= link_to portfolio_path(user.find_portfolio(@group.id)), class: "list-group-item" do %>
						<p> <%= user.username %> |
						Portfolio net worth: <%= number_to_currency(user.portfolios.where(group_id: @group.id).take.current_value) %></p>
						<% end %>
				<% end %>
			</div>
		</div>

		<div class="col-sm-6">
			<h2>Group Logs</h2>
			<div class="group-logs">
				<% @logs.each do |log| %>
					<div class="list-group-item">
						<div class="row">
							<div class="col-sm-3">
								<%= log.user.username %>
							</div>
							<div class="col-sm-3">
								<%= log.action %>
							</div>
							<div class="col-sm-3">
								<%= number_to_currency(log.return_amount) %>
							</div>
							<% if log.base_stock.present? %>
								<div class="col-sm-3">
									<%= log.base_stock.name %>
								</div>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>