config/routes.rb
Rails.application.routes.draw do

	root to: "users#home"

  resources :portfolios
	get '/stack', to: 'users#stack'
  resources :users
  resources :groups
  post "/groups/:id/participation", to: "groups#join"

  resources :stocks, controller: 'base_stocks'
  resources :owned_stocks

# User session routes
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!

	has_many :logs
  has_many :participations
	has_many :portfolios
	has_many :groups, through: :participations

	validates :email, :username, presence: true
	validates :email, :username, uniqueness: true

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  def stock_count(stock)
  	stock_info = {}
  	self.portfolios.each do |portfolio|
  		group_name = portfolio.group.name
  		stock = portfolio.owned_stocks.where(ticker: stock.ticker) if portfolio.owned_stocks.present?
  		count = stock.quantity if stock.present?

  		stock_info[group_name.parameterize.underscore.to_sym] = count if count.present?
  	end
  	stock_info
  end

  def find_portfolio(group_id)
    self.portfolios.find_by(group_id: group_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:home, :index, :new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def home
    @gainers = BaseStock.order("percent_change DESC").limit(10)
    @losers = BaseStock.order("percent_change ASC").limit(10)
  end

  def stack
  end

  def index
  end

  def show
    @user.portfolios.each do |portfolio|
      portfolio.calculate_value
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(:root, notice: 'User was successfully created')
    else
      flash[:warning] = "Profile could not be created"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user.destroy
    redirect_to :root
  end
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :username)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<div class="form-group">
		<%= f.label :username %>
		<%= f.text_field :username, class: "form-control" %>
	</div>
	<div class="form-group">
	  <%= f.label :email %>
	  <%= f.text_field :email, class: "form-control" %>
	</div>
  <div class="form-group">
	  <%= f.label :first_name %>
	  <%= f.text_field :first_name, class: "form-control" %>
	</div>
  <div class="form-group">
	  <%= f.label :last_name %>
	  <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up", class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/_gainers.erb
<h3>% Gainers</h3>
<% @gainers.each do |stock| %>
	<%= link_to stock_path(stock), class: "list-group-item" do %>
		<div class="row">
			<span class="col-xs-6"><%= stock.name %> (<%= stock.ticker %>)</span> <span class="col-xs-3 per-change"><%= (stock.percent_change*100).round(2) %>%</span> <span class="col-xs-3"><%= number_to_currency(stock.current_market_price) %></span>
		</div>
	<% end %>
<% end %>

app/views/users/_losers.html.erb
<h3>% Losers</h3>
<% @losers.each do |stock| %>
	<%= link_to stock_path(stock), class: "list-group-item" do %>
		<div class="row">
			<span class="col-xs-6"><%= stock.name %> (<%= stock.ticker %>)</span> <span class="col-xs-3 per-change"><%= (stock.percent_change*100).round(2) %>%</span> <span class="col-xs-3"><%= number_to_currency(stock.current_market_price) %></span>
		</div>
	<% end %>
<% end %>

app/views/users/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="welcome-header">Welcome to Fantasy Finance</h1>
    <div class="row">
      <p class="col-sm-4">Build your dream portfolio</p>
    </div>
    <div class="row">
      <p class="col-sm-4 col-sm-offset-4">Compete against your friends</p>
    </div>
    <div class="row">
      <p class="col-sm-4 col-sm-offset-8">Become a Market Master</p>
    </div>
    <div class="row jumbotron-btn-row">
      <h4>Get Started</h4>
    </div>
    <div class="row jumbotron-btn-row">
      <% if current_user %>
        <%= link_to 'Groups', groups_url, class:'btn btn-default' %>
        <%= link_to 'Stocks', stocks_url, class:'btn btn-default' %>
        <%= link_to 'Profile', user_url(current_user), class:'btn btn-default' %>
      <% else %>
        <%= link_to 'Login', new_user_session_url, class:'btn btn-default'%>
        <%= link_to 'Sign Up', new_user_url, class:'btn btn-default'%>
      <% end %>
    </div>
  </div>
</div>
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 movers">
        <h2>Today's Biggest Movers</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 movers">
        <%= render 'gainers' %>
      </div>
      <div class="col-sm-6 movers">
        <%= render 'losers' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Create a new profile</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
	<div class="container">
		<h1><%=@user.username%></h1>
		<p><%=@user.first_name%> <%=@user.last_name %></p>
	</div>
</div>
<div class="container">
	<div class="list-group">
		<h2>Your current games:</h2>
		<% if current_user.groups.any? %>
			<% @user.portfolios.each do |portfolio| %>
			<a class="list-group-item" href=<%=portfolio_url(portfolio)%> ><%=portfolio.group.name%> | Your Portfolio Net Worth: <%= number_to_currency(portfolio.current_value) %> </a>
			<% end %>
		<% else %>
			<p><%= link_to "Find", groups_url %> or <%= link_to "Start", new_group_url %> to start trading.</p>
		<% end %>
	</div>
</div>

app/views/users/stack.html.erb
<div class="container" id="stack-wrapper">
  <div class="row">
    <div class="col-xs-12 tech-header">
      <h1>Technology Stack</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 front-end">
      <h2>Front End</h2>
      <img class="tech-img" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/768px-JavaScript-logo.png" alt="">
      <img class="tech-img" src="http://www.brandsoftheworld.com/sites/default/files/styles/logo-thumbnail/public/082014/bootstrap_0.png?itok=SQYPc-Am" alt="Bootstrap">
    </div>
    <div class="col-sm-6 back-end">
      <h2>Back End</h2>
      <img class="tech-img" src="https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/Ruby_on_Rails.svg/791px-Ruby_on_Rails.svg.png" alt="">
      <img class="tech-img" src="https://worldvectorlogo.com/logos/nodejs-icon.svg" alt="">


    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 tech-second">
      <img class="tech-img-2 sass" src="http://www.bennpearson.co.uk/public/img/info/sass.svg" alt="">
      <img class="tech-img-2" src="https://www.shoeboxed.com/wp-content/themes/sbx/images/yahoo_finance_logo.png" alt="">
      <img class="tech-img-2" src="https://upload.wikimedia.org/wikipedia/zh/thumb/e/ec/Heroku_logo.svg/1280px-Heroku_logo.svg.png" alt="">
    </div>
  </div>
  <div class="row">
    <div class="col-xs-offset-5 col-xs-2 gems">
      <h2>Gems</h2>
      <div class="gem-list">
        <img src="https://worldvectorlogo.com/logos/rubygems.svg" alt=""><p>Sorcery</p>
      </div>
      <div class="gem-list">
        <img src="https://worldvectorlogo.com/logos/rubygems.svg" alt=""><p>Will_Paginate</p>
      </div>
      <div class="gem-list">
        <img src="https://worldvectorlogo.com/logos/rubygems.svg" alt=""><p>yahoo_finance_lib</p>
      </div>
    </div>
  </div>
</div>