config/routes.rb
Rails.application.routes.draw do

	root to: "users#home"

  resources :portfolios
	get '/stack', to: 'users#stack'
  resources :users
  resources :groups
  post "/groups/:id/participation", to: "groups#join"

  resources :stocks, controller: 'base_stocks'
  resources :owned_stocks

# User session routes
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyFinancial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width" />
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-default">
<div class="container-fluid">
	<div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		<span class="sr-only">Toggle Navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
  <a href="/" class="navbar-brand">Fantasy Finance</a>
	</div>


<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Groups", groups_url %></li>
        <li><%= link_to "Stocks", stocks_url %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

      	<% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Portfolios <span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <% current_user.portfolios.each do |portfolio| %>
                <li><a href=<%=portfolio_url(portfolio)%>> <%= current_user.username %>'s Portfolio in <%= portfolio.group.name %> </a></li>
              <% end %>
            </ul>
          </li>
        	<li><%=link_to 'Profile', user_path(current_user)%></li>
        	<li><%= link_to 'Logout', :logout, method: :post%></li>
    		<% else %>
    			<li><%=link_to 'Sign Up', new_user_path%></li>
    			<li><%=link_to 'Login', :login%></li>
    		<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


	<%if flash[:notice]%>
		<div class="alert alert-success"><%= flash[:notice] %></div>
 	<% elsif flash[:warning]%>
		<div class="alert alert-warning"><%= flash[:warning] %></div>
	<% end %>

<div id="wrapper">
  <%= yield %>
</div>

<div id="footer">
  <div class="container">
    <div class="col-xs-4">&#169; Fantasy Finance</div>
    <div class="col-xs-4 col-xs-offset-4 tech-stack-link"><%= link_to "Technology Stack", stack_url%> </div>
  </div>
</div>

</body>
</html>